Public Class ReporteCostoTotalEnUnaZonaDeTrabajoPorRubrosAgroinper
    Inherits BaseBL

    'Private dvMessage As Object
    'Private lblResult As Object

    Public Sub New(strUsuario As String)
        MyBase.New(strUsuario)
    End Sub

    Public Function getDataZonaTrabajo(ByVal IdUsuario As String, ByVal id As String, ByVal desc As String) As ADODB.Recordset
        Dim adoTabla As ADODB.Recordset
        'Dim DBconn As ADODB.Connection = GenericMethods.SetupConnection(LoggedUser)
        Dim ssql As String = "SELECT ZONA_TRABAJO.id_zonatrabajo,ZONA_TRABAJO.descripcion,campana,hectareas FROM ZONA_TRABAJO INNER JOIN USUARIOCCOSTOS ON ZONA_TRABAJO.id_fundo = USUARIOCCOSTOS.id_fundo WHERE (ZONA_TRABAJO.estado <> 0) AND (ZONA_TRABAJO.tipo = 'C') AND (USUARIOCCOSTOS.Id_usuario = '" & IdUsuario & "') ORDER BY ZONA_TRABAJO.descripcion"

        adoTabla = New ADODB.Recordset
        adoTabla.Open(ssql, DBConn, ADODB.CursorTypeEnum.adOpenStatic, ADODB.LockTypeEnum.adLockReadOnly)

        Return adoTabla
    End Function

    Public Function Refresh_Query(ByVal pSearchFilter As String, ByVal pDetailLevelSelected As String, ByVal pCboMoneda As Integer, ByVal pMatrizZT As String, ByVal pstrCampoCampaña As String, ByVal pdtfechamin As String, ByVal pdtfechamax As String, ByVal pedtNumeroCampana As String) As ADODB.Recordset
        Dim strSQL As String
        Dim rsReporte As New ADODB.Recordset
        Dim dtFechaFrom As DateTime
        Dim dtFechaTo As DateTime
        Dim fechaValida As Boolean = True
        Dim fechaFrom As DateTime = DateTime.Now
        Dim fechaTo As DateTime = DateTime.Now

        If pSearchFilter <> "Campaña" Then
            If Not String.IsNullOrEmpty(dtFechaFrom) Then
                fechaValida = DateTime.TryParseExact(pdtfechamin, "dd/MM/yyyy", Globalization.CultureInfo.CurrentCulture, Globalization.DateTimeStyles.None, fechaFrom)
            End If

            If Not String.IsNullOrEmpty(dtFechaTo) Then
                fechaValida = (fechaValida And DateTime.TryParseExact(pdtfechamax, "dd/MM/yyyy", Globalization.CultureInfo.CurrentCulture, Globalization.DateTimeStyles.None, fechaTo))
            End If

            If Not fechaValida Then
                'dvMessage.Visible = True
                'dvMessage.Attributes.Add("class", "alert alert-danger")
                'lblResult.Text =Resource1.str99991
                Exit Function

            End If
        End If

        If pDetailLevelSelected = "Detalle" Then
            If pSearchFilter = "Campaña" Then
                If pCboMoneda = 0 Then
                    strSQL = "SELECT ZONA_TRABAJO.id_zonatrabajo AS ZONA_TRABAJO_id_zonatrabajo, ZONA_TRABAJO.descripcion AS ZONA_TRABAJO_descripcion, ZONA_TRABAJO.hectareas AS ZONA_TRABAJO_hectareas, CULTIVOS.id_cultivo AS CULTIVOS_id_cultivo, CULTIVOS.descripcion AS CULTIVOS_descripcion, ETAPAS.id_etapa AS ETAPAS_id_etapa, ETAPAS.descripcion AS ETAPAS_descripcion, ETAPAS.ubicacion_cc AS ETAPAS_ubicacion_cc, ACTIVIDADES.id_actividad AS ACTIVIDADES_id_actividad, ACTIVIDADES.descripcion AS ACTIVIDADES_descripcion, ACTIVIDADES.ubicacion_cc AS ACTIVIDADES_ubicacion_cc, TIPO_COSTO.orden AS TIPO_COSTO_orden, upper(TIPO_COSTO.descripcion) AS TIPO_COSTO_descripcion, COSTOS.tipo_costo AS COSTOS_tipo_costo, " & "case when [tipo_costo]='I' then PRODUCTOS.descripcion else case when [tipo_costo]='H' then PERSONAL.nombre else  case when [tipo_costo]='M' then MAQUINAS.descripcion else case when [tipo_costo]='R' then MAQUINAS.descripcion else case when [tipo_costo]='O' then COSTOS.observaciones else '' end end end end end AS COSTOS_descripcion, COSTOS.cantidad AS COSTOS_cantidad, COSTOS.monto_standar AS COSTOS_monto_standar, COSTOS.fecha AS COSTOS_fecha, COSTOS.campana AS COSTOS_campana,costos.numero_doc " & "FROM (CULTIVOS INNER JOIN ((((((COSTOS INNER JOIN ACTIVIDADES ON COSTOS.id_actividad = ACTIVIDADES.id_actividad) INNER JOIN ETAPAS ON ACTIVIDADES.id_etapa = ETAPAS.id_etapa) left outer JOIN MAQUINAS ON COSTOS.id_maquinaria = MAQUINAS.id_maquinaria) INNER JOIN PERSONAL ON COSTOS.id_personal = PERSONAL.id_personal) INNER JOIN PRODUCTOS ON COSTOS.id_producto = PRODUCTOS.id_producto) INNER JOIN ZONA_TRABAJO ON COSTOS.id_zonatrabajo = ZONA_TRABAJO.id_zonatrabajo) ON CULTIVOS.id_cultivo = ZONA_TRABAJO.id_cultivo) INNER JOIN TIPO_COSTO ON COSTOS.tipo_costo = TIPO_COSTO.id_tipocosto " & "Where   COSTOS.PRECIO_CONTABLE>=0 AND COSTOS.Tipo_Costo <> 'C' and COSTOS.Tipo_Costo <> 'V' And COSTOS.Tipo_Costo <> 'T' And COSTOS.Tipo_Costo <> 'E' And COSTOS.Tipo_Costo <> 'S' And (COSTOS.tipo_costo)<>'A'  And COSTOS.Tipo_Costo <> 'D' And (((ZONA_TRABAJO.id_zonatrabajo) = '" & pMatrizZT & "') " & "And (" & pstrCampoCampaña & "= " & pedtNumeroCampana & ")) " & "ORDER BY ZONA_TRABAJO.descripcion, CULTIVOS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.ubicacion_cc, TIPO_COSTO.orden, case when [tipo_costo]='I' then PRODUCTOS.descripcion else case when [tipo_costo]='H' then PERSONAL.nombre else  case when [tipo_costo]='M' then MAQUINAS.descripcion else case when [tipo_costo]='R' then MAQUINAS.descripcion else case when [tipo_costo]='O' then COSTOS.observaciones else '' end end end end end, COSTOS.fecha"
                Else
                    strSQL = "SELECT ZONA_TRABAJO.id_zonatrabajo AS ZONA_TRABAJO_id_zonatrabajo, ZONA_TRABAJO.descripcion AS ZONA_TRABAJO_descripcion, ZONA_TRABAJO.hectareas AS ZONA_TRABAJO_hectareas, CULTIVOS.id_cultivo AS CULTIVOS_id_cultivo, CULTIVOS.descripcion AS CULTIVOS_descripcion, ETAPAS.id_etapa AS ETAPAS_id_etapa, ETAPAS.descripcion AS ETAPAS_descripcion, ETAPAS.ubicacion_cc AS ETAPAS_ubicacion_cc, ACTIVIDADES.id_actividad AS ACTIVIDADES_id_actividad, ACTIVIDADES.descripcion AS ACTIVIDADES_descripcion, ACTIVIDADES.ubicacion_cc AS ACTIVIDADES_ubicacion_cc, TIPO_COSTO.orden AS TIPO_COSTO_orden, upper(TIPO_COSTO.descripcion) AS TIPO_COSTO_descripcion, COSTOSME.tipo_costo AS COSTOS_tipo_costo, " & "case when [tipo_costo]='I' then PRODUCTOS.descripcion else case when [tipo_costo]='H' then PERSONAL.nombre else  case when [tipo_costo]='M' then MAQUINAS.descripcion else case when [tipo_costo]='R' then MAQUINAS.descripcion else case when [tipo_costo]='O' then COSTOSme.observaciones else '' end end end end end AS COSTOS_descripcion, COSTOSME.cantidad AS COSTOS_cantidad, COSTOSME.MS AS COSTOS_monto_standar, COSTOSME.fecha AS COSTOS_fecha, COSTOSME.campana AS COSTOS_campana,costosme.numero_doc " & "FROM (CULTIVOS INNER JOIN ((((((COSTOSME INNER JOIN ACTIVIDADES ON COSTOSME.id_actividad = ACTIVIDADES.id_actividad) INNER JOIN ETAPAS ON ACTIVIDADES.id_etapa = ETAPAS.id_etapa) left outer JOIN MAQUINAS  ON COSTOSME.id_maquinaria = MAQUINAS.id_maquinaria) INNER JOIN PERSONAL ON COSTOSME.id_personal = PERSONAL.id_personal) INNER JOIN PRODUCTOS ON COSTOSME.id_producto = PRODUCTOS.id_producto) INNER JOIN ZONA_TRABAJO ON COSTOSME.id_zonatrabajo = ZONA_TRABAJO.id_zonatrabajo) ON CULTIVOS.id_cultivo = ZONA_TRABAJO.id_cultivo) INNER JOIN TIPO_COSTO ON COSTOSME.tipo_costo = TIPO_COSTO.id_tipocosto " & "Where     COSTOSME.PC>=0 AND COSTOSME.Tipo_Costo <> 'C' And COSTOSME.Tipo_Costo <> 'V' AND COSTOSME.Tipo_Costo <> 'T' And COSTOSME.Tipo_Costo <> 'E' And COSTOSME.Tipo_Costo <> 'S'  And (COSTOSME.tipo_costo)<>'A'  And COSTOSME.Tipo_Costo <> 'D' And (((ZONA_TRABAJO.id_zonatrabajo) = '" & pMatrizZT & "') " & "And (" & pstrCampoCampaña & "= " & pedtNumeroCampana & ")) " & "ORDER BY ZONA_TRABAJO.descripcion, CULTIVOS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.ubicacion_cc, TIPO_COSTO.orden, case when [tipo_costo]='I' then PRODUCTOS.descripcion else case when [tipo_costo]='H' then PERSONAL.nombre else  case when [tipo_costo]='M' then MAQUINAS.descripcion else case when [tipo_costo]='R' then MAQUINAS.descripcion else case when [tipo_costo]='O' then COSTOSme.observaciones else '' end end end end end, COSTOSME.fecha"
                End If
            Else

                If pCboMoneda = 0 Then
                    strSQL = "SELECT ZONA_TRABAJO.id_zonatrabajo AS ZONA_TRABAJO_id_zonatrabajo, ZONA_TRABAJO.descripcion AS ZONA_TRABAJO_descripcion, ZONA_TRABAJO.hectareas AS ZONA_TRABAJO_hectareas, CULTIVOS.id_cultivo AS CULTIVOS_id_cultivo, CULTIVOS.descripcion AS CULTIVOS_descripcion, ETAPAS.id_etapa AS ETAPAS_id_etapa, ETAPAS.descripcion AS ETAPAS_descripcion, ETAPAS.ubicacion_cc AS ETAPAS_ubicacion_cc, ACTIVIDADES.id_actividad AS ACTIVIDADES_id_actividad, ACTIVIDADES.descripcion AS ACTIVIDADES_descripcion, ACTIVIDADES.ubicacion_cc AS ACTIVIDADES_ubicacion_cc, TIPO_COSTO.orden AS TIPO_COSTO_orden, upper(TIPO_COSTO.descripcion) AS TIPO_COSTO_descripcion, COSTOS.tipo_costo AS COSTOS_tipo_costo, " & "case when [tipo_costo]='I' then PRODUCTOS.descripcion else case when [tipo_costo]='H' then PERSONAL.nombre else  case when [tipo_costo]='M' then MAQUINAS.descripcion else case when [tipo_costo]='R' then MAQUINAS.descripcion else case when [tipo_costo]='O' then COSTOS.observaciones else '' end end end end end AS COSTOS_descripcion, " & "COSTOS.cantidad AS COSTOS_cantidad, COSTOS.monto_standar AS COSTOS_monto_standar, COSTOS.fecha AS COSTOS_fecha, COSTOS.campana AS COSTOS_campana,costos.numero_doc " & "FROM (CULTIVOS INNER JOIN ((((((COSTOS INNER JOIN ACTIVIDADES ON COSTOS.id_actividad = ACTIVIDADES.id_actividad) INNER JOIN ETAPAS ON ACTIVIDADES.id_etapa = ETAPAS.id_etapa) left outer JOIN MAQUINAS  ON COSTOS.id_maquinaria = MAQUINAS.id_maquinaria) INNER JOIN PERSONAL ON COSTOS.id_personal = PERSONAL.id_personal) INNER JOIN PRODUCTOS ON COSTOS.id_producto = PRODUCTOS.id_producto) INNER JOIN ZONA_TRABAJO ON COSTOS.id_zonatrabajo = ZONA_TRABAJO.id_zonatrabajo) ON CULTIVOS.id_cultivo = ZONA_TRABAJO.id_cultivo) INNER JOIN TIPO_COSTO ON COSTOS.tipo_costo = TIPO_COSTO.id_tipocosto " & "Where  COSTOS.PRECIO_CONTABLE>=0 AND COSTOS.Tipo_Costo <> 'C' And COSTOS.Tipo_Costo <> 'V' And COSTOS.Tipo_Costo <> 'T' And COSTOS.Tipo_Costo <> 'E' And COSTOS.Tipo_Costo <> 'S' And (COSTOS.tipo_costo)<>'A'  And COSTOS.Tipo_Costo <> 'D' And (((ZONA_TRABAJO.id_zonatrabajo) = '" & pMatrizZT & "') " & "And ((COSTOS.fecha) >= convert(datetime,replace('" & fechaFrom.ToString("yyyyMMdd") & "',',','/')) " & "And (COSTOS.fecha) <= convert(datetime,replace('" & fechaTo.ToString("yyyyMMdd") & "',',','/')))) " & "ORDER BY ZONA_TRABAJO.descripcion, CULTIVOS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.ubicacion_cc, TIPO_COSTO.orden, case when [tipo_costo]='I' then PRODUCTOS.descripcion else case when [tipo_costo]='H' then PERSONAL.nombre else  case when [tipo_costo]='M' then MAQUINAS.descripcion else case when [tipo_costo]='R' then MAQUINAS.descripcion else case when [tipo_costo]='O' then COSTOS.observaciones else '' end end end end end, COSTOS.fecha"
                Else
                    strSQL = "SELECT ZONA_TRABAJO.id_zonatrabajo AS ZONA_TRABAJO_id_zonatrabajo, ZONA_TRABAJO.descripcion AS ZONA_TRABAJO_descripcion, ZONA_TRABAJO.hectareas AS ZONA_TRABAJO_hectareas, CULTIVOS.id_cultivo AS CULTIVOS_id_cultivo, CULTIVOS.descripcion AS CULTIVOS_descripcion, ETAPAS.id_etapa AS ETAPAS_id_etapa, ETAPAS.descripcion AS ETAPAS_descripcion, ETAPAS.ubicacion_cc AS ETAPAS_ubicacion_cc, ACTIVIDADES.id_actividad AS ACTIVIDADES_id_actividad, ACTIVIDADES.descripcion AS ACTIVIDADES_descripcion, ACTIVIDADES.ubicacion_cc AS ACTIVIDADES_ubicacion_cc, TIPO_COSTO.orden AS TIPO_COSTO_orden, upper(TIPO_COSTO.descripcion) AS TIPO_COSTO_descripcion, COSTOSME.tipo_costo AS COSTOS_tipo_costo, " & "case when [tipo_costo]='I' then PRODUCTOS.descripcion else case when [tipo_costo]='H' then PERSONAL.nombre else  case when [tipo_costo]='M' then MAQUINAS.descripcion else case when [tipo_costo]='R' then MAQUINAS.descripcion else case when [tipo_costo]='O' then COSTOSme.observaciones else '' end end end end end AS COSTOS_descripcion, " & "COSTOSME.cantidad AS COSTOS_cantidad, COSTOSME.MS AS COSTOS_monto_standar, COSTOSME.fecha AS COSTOS_fecha, COSTOSME.campana AS COSTOS_campana,costosme.numero_doc " & "FROM (CULTIVOS INNER JOIN ((((((COSTOSME INNER JOIN ACTIVIDADES ON COSTOSME.id_actividad = ACTIVIDADES.id_actividad) INNER JOIN ETAPAS ON ACTIVIDADES.id_etapa = ETAPAS.id_etapa) left outer JOIN MAQUINAS  ON COSTOSME.id_maquinaria = MAQUINAS.id_maquinaria) INNER JOIN PERSONAL ON COSTOSME.id_personal = PERSONAL.id_personal) INNER JOIN PRODUCTOS ON COSTOSME.id_producto = PRODUCTOS.id_producto) INNER JOIN ZONA_TRABAJO ON COSTOSME.id_zonatrabajo = ZONA_TRABAJO.id_zonatrabajo) ON CULTIVOS.id_cultivo = ZONA_TRABAJO.id_cultivo) INNER JOIN TIPO_COSTO ON COSTOSME.tipo_costo = TIPO_COSTO.id_tipocosto " & "Where    COSTOSME.PC>=0 AND COSTOSME.Tipo_Costo <> 'C' And COSTOSME.Tipo_Costo <> 'V' And COSTOSME.Tipo_Costo <> 'T' And COSTOSME.Tipo_Costo <> 'E' And COSTOSME.Tipo_Costo <> 'S' And (COSTOSME.tipo_costo)<>'A'  And COSTOSME.Tipo_Costo <> 'D' And (((ZONA_TRABAJO.id_zonatrabajo) = '" & pMatrizZT & "') " & "And ((COSTOSME.fecha) >= convert(datetime,replace('" & fechaFrom.ToString("yyyyMMdd") & "',',','/')) " & "And (COSTOSME.fecha) <= convert(datetime,replace('" & fechaTo.ToString("yyyyMMdd") & "',',','/')))) " & "ORDER BY ZONA_TRABAJO.descripcion, CULTIVOS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.ubicacion_cc, TIPO_COSTO.orden, case when [tipo_costo]='I' then PRODUCTOS.descripcion else case when [tipo_costo]='H' then PERSONAL.nombre else  case when [tipo_costo]='M' then MAQUINAS.descripcion else case when [tipo_costo]='R' then MAQUINAS.descripcion else case when [tipo_costo]='O' then COSTOSme.observaciones else '' end end end end end, COSTOSME.fecha"
                End If
            End If
        Else
            If pSearchFilter = "Campaña" Then
                If pCboMoneda = 0 Then
                    strSQL = "SELECT ZONA_TRABAJO.id_zonatrabajo AS ZONA_TRABAJO_id_zonatrabajo, ZONA_TRABAJO.descripcion AS ZONA_TRABAJO_descripcion, ZONA_TRABAJO.hectareas AS ZONA_TRABAJO_hectareas, CULTIVOS.id_cultivo AS CULTIVOS_id_cultivo, CULTIVOS.descripcion AS CULTIVOS_descripcion, ETAPAS.id_etapa AS ETAPAS_id_etapa, ETAPAS.descripcion AS ETAPAS_descripcion, ETAPAS.ubicacion_cc AS ETAPAS_ubicacion_cc, ACTIVIDADES.id_actividad AS ACTIVIDADES_id_actividad, ACTIVIDADES.descripcion AS ACTIVIDADES_descripcion, ACTIVIDADES.ubicacion_cc AS ACTIVIDADES_ubicacion_cc, TIPO_COSTO.orden AS TIPO_COSTO_orden, upper(TIPO_COSTO.descripcion) AS TIPO_COSTO_descripcion, COSTOS.tipo_costo AS COSTOS_tipo_costo, " & "case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end AS INSUMOS_descripcion, Sum(COSTOS.cantidad) AS COSTOS_cantidad, Sum(COSTOS.monto_standar) AS COSTOS_monto_standar " & "FROM (CULTIVOS INNER JOIN ((((((COSTOS INNER JOIN ACTIVIDADES ON COSTOS.id_actividad = ACTIVIDADES.id_actividad) INNER JOIN ETAPAS ON ACTIVIDADES.id_etapa = ETAPAS.id_etapa) left outer JOIN MAQUINAS  ON COSTOS.id_maquinaria = MAQUINAS.id_maquinaria) INNER JOIN PERSONAL ON COSTOS.id_personal = PERSONAL.id_personal) INNER JOIN PRODUCTOS ON COSTOS.id_producto = PRODUCTOS.id_producto) INNER JOIN ZONA_TRABAJO ON COSTOS.id_zonatrabajo = ZONA_TRABAJO.id_zonatrabajo) ON CULTIVOS.id_cultivo = ZONA_TRABAJO.id_cultivo) INNER JOIN TIPO_COSTO ON COSTOS.tipo_costo = TIPO_COSTO.id_tipocosto " & "Where    COSTOS.PRECIO_CONTABLE>=0 AND COSTOS.Tipo_Costo <> 'C' And COSTOS.Tipo_Costo <> 'V' And COSTOS.Tipo_Costo <> 'T' And COSTOS.Tipo_Costo <> 'E' And COSTOS.Tipo_Costo <> 'S' And (COSTOS.tipo_costo)<>'A'  And COSTOS.Tipo_Costo <> 'D' And ((" & pstrCampoCampaña & "= " & pedtNumeroCampana & ")) " & "GROUP BY ZONA_TRABAJO.id_zonatrabajo, ZONA_TRABAJO.descripcion, ZONA_TRABAJO.hectareas, CULTIVOS.id_cultivo, CULTIVOS.descripcion, ETAPAS.id_etapa, ETAPAS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.id_actividad, ACTIVIDADES.descripcion, ACTIVIDADES.ubicacion_cc, TIPO_COSTO.orden, upper(TIPO_COSTO.descripcion), COSTOS.tipo_costo, case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end " & "Having (((ZONA_TRABAJO.id_zonatrabajo) = '" & pMatrizZT & "')) " & "ORDER BY ZONA_TRABAJO.descripcion, CULTIVOS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.ubicacion_cc, Sum(COSTOS.monto_standar) DESC, TIPO_COSTO.orden, case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end"
                Else
                    strSQL = "SELECT ZONA_TRABAJO.id_zonatrabajo AS ZONA_TRABAJO_id_zonatrabajo, ZONA_TRABAJO.descripcion AS ZONA_TRABAJO_descripcion, ZONA_TRABAJO.hectareas AS ZONA_TRABAJO_hectareas, CULTIVOS.id_cultivo AS CULTIVOS_id_cultivo, CULTIVOS.descripcion AS CULTIVOS_descripcion, ETAPAS.id_etapa AS ETAPAS_id_etapa, ETAPAS.descripcion AS ETAPAS_descripcion, ETAPAS.ubicacion_cc AS ETAPAS_ubicacion_cc, ACTIVIDADES.id_actividad AS ACTIVIDADES_id_actividad, ACTIVIDADES.descripcion AS ACTIVIDADES_descripcion, ACTIVIDADES.ubicacion_cc AS ACTIVIDADES_ubicacion_cc, TIPO_COSTO.orden AS TIPO_COSTO_orden, upper(TIPO_COSTO.descripcion) AS TIPO_COSTO_descripcion, COSTOSME.tipo_costo AS COSTOS_tipo_costo, " & "case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end AS INSUMOS_descripcion, Sum(COSTOSME.cantidad) AS COSTOS_cantidad, Sum(COSTOSME.MS) AS COSTOS_monto_standar " & "FROM (CULTIVOS INNER JOIN ((((((COSTOSME INNER JOIN ACTIVIDADES ON COSTOSME.id_actividad = ACTIVIDADES.id_actividad) INNER JOIN ETAPAS ON ACTIVIDADES.id_etapa = ETAPAS.id_etapa) left outer JOIN MAQUINAS  ON COSTOSME.id_maquinaria = MAQUINAS.id_maquinaria) INNER JOIN PERSONAL ON COSTOSME.id_personal = PERSONAL.id_personal) INNER JOIN PRODUCTOS ON COSTOSME.id_producto = PRODUCTOS.id_producto) INNER JOIN ZONA_TRABAJO ON COSTOSME.id_zonatrabajo = ZONA_TRABAJO.id_zonatrabajo) ON CULTIVOS.id_cultivo = ZONA_TRABAJO.id_cultivo) INNER JOIN TIPO_COSTO ON COSTOSME.tipo_costo = TIPO_COSTO.id_tipocosto " & "Where     COSTOSME.PC>=0 AND COSTOSME.Tipo_Costo <> 'C' And COSTOSME.Tipo_Costo <> 'V' And COSTOSME.Tipo_Costo <> 'T' And COSTOSME.Tipo_Costo <> 'E' And COSTOSME.Tipo_Costo <> 'S'  And COSTOSME.Tipo_Costo <> 'D' And (COSTOSME.tipo_costo)<>'A' And ((" & pstrCampoCampaña & "= " & pedtNumeroCampana & ")) " & "GROUP BY ZONA_TRABAJO.id_zonatrabajo, ZONA_TRABAJO.descripcion, ZONA_TRABAJO.hectareas, CULTIVOS.id_cultivo, CULTIVOS.descripcion, ETAPAS.id_etapa, ETAPAS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.id_actividad, ACTIVIDADES.descripcion, ACTIVIDADES.ubicacion_cc, TIPO_COSTO.orden, upper(TIPO_COSTO.descripcion), COSTOSME.tipo_costo, case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end " & "Having (((ZONA_TRABAJO.id_zonatrabajo) = '" & pMatrizZT & "')) " & "ORDER BY ZONA_TRABAJO.descripcion, CULTIVOS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.ubicacion_cc, Sum(COSTOSME.MS) DESC, TIPO_COSTO.orden, case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end"
                End If
            Else
                If pCboMoneda = 0 Then
                    strSQL = "SELECT ZONA_TRABAJO.id_zonatrabajo AS ZONA_TRABAJO_id_zonatrabajo, ZONA_TRABAJO.descripcion AS ZONA_TRABAJO_descripcion, ZONA_TRABAJO.hectareas AS ZONA_TRABAJO_hectareas, CULTIVOS.id_cultivo AS CULTIVOS_id_cultivo, CULTIVOS.descripcion AS CULTIVOS_descripcion, ETAPAS.id_etapa AS ETAPAS_id_etapa, ETAPAS.descripcion AS ETAPAS_descripcion, ETAPAS.ubicacion_cc AS ETAPAS_ubicacion_cc, ACTIVIDADES.id_actividad AS ACTIVIDADES_id_actividad, ACTIVIDADES.descripcion AS ACTIVIDADES_descripcion, ACTIVIDADES.ubicacion_cc AS ACTIVIDADES_ubicacion_cc, TIPO_COSTO.orden AS TIPO_COSTO_orden, upper(TIPO_COSTO.descripcion) AS TIPO_COSTO_descripcion, COSTOS.tipo_costo AS COSTOS_tipo_costo, " & "case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end AS INSUMOS_descripcion, Sum(COSTOS.cantidad) AS COSTOS_cantidad, Sum(COSTOS.monto_standar) AS COSTOS_monto_standar " & "FROM (CULTIVOS INNER JOIN ((((((COSTOS INNER JOIN ACTIVIDADES ON COSTOS.id_actividad = ACTIVIDADES.id_actividad) INNER JOIN ETAPAS ON ACTIVIDADES.id_etapa = ETAPAS.id_etapa) left outer JOIN MAQUINAS  ON COSTOS.id_maquinaria = MAQUINAS.id_maquinaria) INNER JOIN PERSONAL ON COSTOS.id_personal = PERSONAL.id_personal) INNER JOIN PRODUCTOS ON COSTOS.id_producto = PRODUCTOS.id_producto) INNER JOIN ZONA_TRABAJO ON COSTOS.id_zonatrabajo = ZONA_TRABAJO.id_zonatrabajo) ON CULTIVOS.id_cultivo = ZONA_TRABAJO.id_cultivo) INNER JOIN TIPO_COSTO ON COSTOS.tipo_costo = TIPO_COSTO.id_tipocosto " & "Where    COSTOS.PRECIO_CONTABLE>=0 AND COSTOS.Tipo_Costo <>'C' And COSTOS.Tipo_Costo <> 'V' And COSTOS.Tipo_Costo <> 'E' And COSTOS.Tipo_Costo <> 'S'  And (COSTOS.tipo_costo)<>'A'  And COSTOS.Tipo_Costo <> 'D' And COSTOS.Tipo_Costo <> 'T' And (((COSTOS.fecha) >= convert(datetime,replace('" & DateTime.Parse(pdtfechamin).ToString("yyyyMMdd") & "',',','/')) " & "And (COSTOS.fecha) <= convert(datetime,replace('" & DateTime.Parse(pdtfechamax).ToString("yyyyMMdd") & "',',','/')))) " & "GROUP BY ZONA_TRABAJO.id_zonatrabajo, ZONA_TRABAJO.descripcion, ZONA_TRABAJO.hectareas, CULTIVOS.id_cultivo, CULTIVOS.descripcion, ETAPAS.id_etapa, ETAPAS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.id_actividad, ACTIVIDADES.descripcion, ACTIVIDADES.ubicacion_cc, TIPO_COSTO.orden, upper(TIPO_COSTO.descripcion), COSTOS.tipo_costo, case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end " & "Having (((ZONA_TRABAJO.id_zonatrabajo) = '" & pMatrizZT & "')) " & "ORDER BY ZONA_TRABAJO.descripcion, CULTIVOS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.ubicacion_cc, Sum(COSTOS.monto_standar) DESC, TIPO_COSTO.orden, case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end"
                Else
                    strSQL = "SELECT ZONA_TRABAJO.id_zonatrabajo AS ZONA_TRABAJO_id_zonatrabajo, ZONA_TRABAJO.descripcion AS ZONA_TRABAJO_descripcion, ZONA_TRABAJO.hectareas AS ZONA_TRABAJO_hectareas, CULTIVOS.id_cultivo AS CULTIVOS_id_cultivo, CULTIVOS.descripcion AS CULTIVOS_descripcion, ETAPAS.id_etapa AS ETAPAS_id_etapa, ETAPAS.descripcion AS ETAPAS_descripcion, ETAPAS.ubicacion_cc AS ETAPAS_ubicacion_cc, ACTIVIDADES.id_actividad AS ACTIVIDADES_id_actividad, ACTIVIDADES.descripcion AS ACTIVIDADES_descripcion, ACTIVIDADES.ubicacion_cc AS ACTIVIDADES_ubicacion_cc, TIPO_COSTO.orden AS TIPO_COSTO_orden, upper(TIPO_COSTO.descripcion) AS TIPO_COSTO_descripcion, COSTOSME.tipo_costo AS COSTOS_tipo_costo, " & "case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end AS INSUMOS_descripcion, Sum(COSTOSME.cantidad) AS COSTOS_cantidad, Sum(COSTOSME.MS) AS COSTOS_monto_standar " & "FROM (CULTIVOS INNER JOIN ((((((COSTOSME INNER JOIN ACTIVIDADES ON COSTOSME.id_actividad = ACTIVIDADES.id_actividad) INNER JOIN ETAPAS ON ACTIVIDADES.id_etapa = ETAPAS.id_etapa) left outer JOIN MAQUINAS  ON COSTOSME.id_maquinaria = MAQUINAS.id_maquinaria) INNER JOIN PERSONAL ON COSTOSME.id_personal = PERSONAL.id_personal) INNER JOIN PRODUCTOS ON COSTOSME.id_producto = PRODUCTOS.id_producto) INNER JOIN ZONA_TRABAJO ON COSTOSME.id_zonatrabajo = ZONA_TRABAJO.id_zonatrabajo) ON CULTIVOS.id_cultivo = ZONA_TRABAJO.id_cultivo) INNER JOIN TIPO_COSTO ON COSTOSME.tipo_costo = TIPO_COSTO.id_tipocosto " & "Where     COSTOSME.PC>=0 AND COSTOSME.Tipo_Costo <>'C'  And COSTOSME.Tipo_Costo <> 'V' And COSTOSME.Tipo_Costo <> 'E' And COSTOSME.Tipo_Costo <> 'S' And (COSTOSME.tipo_costo)<>'A'  And COSTOSME.Tipo_Costo <> 'D' And COSTOSME.Tipo_Costo <> 'T' And (((COSTOSME.fecha) >= convert(datetime,replace('" & DateTime.Parse(pdtfechamin).ToString("yyyyMMdd") & "',',','/')) " & "And (COSTOSME.fecha) <= convert(datetime,replace('" & DateTime.Parse(pdtfechamax).ToString("yyyyMMdd") & "',',','/')))) " & "GROUP BY ZONA_TRABAJO.id_zonatrabajo, ZONA_TRABAJO.descripcion, ZONA_TRABAJO.hectareas, CULTIVOS.id_cultivo, CULTIVOS.descripcion, ETAPAS.id_etapa, ETAPAS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.id_actividad, ACTIVIDADES.descripcion, ACTIVIDADES.ubicacion_cc, TIPO_COSTO.orden, upper(TIPO_COSTO.descripcion), COSTOSME.tipo_costo, case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end " & "Having (((ZONA_TRABAJO.id_zonatrabajo) = '" & pMatrizZT & "')) " & "ORDER BY ZONA_TRABAJO.descripcion, CULTIVOS.descripcion, ETAPAS.ubicacion_cc, ACTIVIDADES.ubicacion_cc, Sum(COSTOSME.MS) DESC, TIPO_COSTO.orden, case when [tipo_costo]='I' then [PRODUCTOS].[descripcion] else '' end"
                End If
            End If
        End If

        rsReporte.Open(strSQL, DBConn, ADODB.CursorTypeEnum.adOpenForwardOnly, ADODB.LockTypeEnum.adLockReadOnly)
        Return rsReporte
    End Function
End Class
