'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.Web
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class sitemap
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Web.sitemap", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cosechas.
        '''</summary>
        Friend Shared ReadOnly Property EnterCostsCosecha_Description() As String
            Get
                Return ResourceManager.GetString("EnterCostsCosecha.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cosechas.
        '''</summary>
        Friend Shared ReadOnly Property EnterCostsCosecha_Title() As String
            Get
                Return ResourceManager.GetString("EnterCostsCosecha.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Costos.
        '''</summary>
        Friend Shared ReadOnly Property EnterCostsForm_Description() As String
            Get
                Return ResourceManager.GetString("EnterCostsForm.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Costos.
        '''</summary>
        Friend Shared ReadOnly Property EnterCostsForm_Title() As String
            Get
                Return ResourceManager.GetString("EnterCostsForm.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingresos Almacen.
        '''</summary>
        Friend Shared ReadOnly Property EnterCostsProduct_Description() As String
            Get
                Return ResourceManager.GetString("EnterCostsProduct.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingresos Almacen.
        '''</summary>
        Friend Shared ReadOnly Property EnterCostsProduct_Title() As String
            Get
                Return ResourceManager.GetString("EnterCostsProduct.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Digitar Costos.
        '''</summary>
        Friend Shared ReadOnly Property EnterCosts_Description() As String
            Get
                Return ResourceManager.GetString("EnterCosts.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Digitar Costos.
        '''</summary>
        Friend Shared ReadOnly Property EnterCosts_Title() As String
            Get
                Return ResourceManager.GetString("EnterCosts.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introducir Datos.
        '''</summary>
        Friend Shared ReadOnly Property EnterData_Description() As String
            Get
                Return ResourceManager.GetString("EnterData.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introducir Datos.
        '''</summary>
        Friend Shared ReadOnly Property EnterData_Title() As String
            Get
                Return ResourceManager.GetString("EnterData.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Linea de Productos.
        '''</summary>
        Friend Shared ReadOnly Property frmLineaProducto_Description() As String
            Get
                Return ResourceManager.GetString("frmLineaProducto.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Linea de Productos.
        '''</summary>
        Friend Shared ReadOnly Property frmLineaProducto_Title() As String
            Get
                Return ResourceManager.GetString("frmLineaProducto.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tablas.
        '''</summary>
        Friend Shared ReadOnly Property Masters_Description() As String
            Get
                Return ResourceManager.GetString("Masters.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tablas.
        '''</summary>
        Friend Shared ReadOnly Property Masters_Title() As String
            Get
                Return ResourceManager.GetString("Masters.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte Comparativo de campañas.
        '''</summary>
        Friend Shared ReadOnly Property ReportCampanas_Description() As String
            Get
                Return ResourceManager.GetString("ReportCampanas.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte Comparativo de campañas.
        '''</summary>
        Friend Shared ReadOnly Property ReportCampanas_Title() As String
            Get
                Return ResourceManager.GetString("ReportCampanas.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte en una Zona de Trabajo por Recursos Detallado.
        '''</summary>
        Friend Shared ReadOnly Property ReporteCostoZTAgroinperDetail_Description() As String
            Get
                Return ResourceManager.GetString("ReporteCostoZTAgroinperDetail.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte en una Zona de Trabajo por Recursos Detallado.
        '''</summary>
        Friend Shared ReadOnly Property ReporteCostoZTAgroinperDetail_Title() As String
            Get
                Return ResourceManager.GetString("ReporteCostoZTAgroinperDetail.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte en una Zona de Trabajo por Recursos Resumido.
        '''</summary>
        Friend Shared ReadOnly Property ReporteCostoZTAgroinperResumido_Description() As String
            Get
                Return ResourceManager.GetString("ReporteCostoZTAgroinperResumido.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte en una Zona de Trabajo por Recursos Resumido.
        '''</summary>
        Friend Shared ReadOnly Property ReporteCostoZTAgroinperResumido_Title() As String
            Get
                Return ResourceManager.GetString("ReporteCostoZTAgroinperResumido.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte de Costo por Kilo.
        '''</summary>
        Friend Shared ReadOnly Property ReportKilo_Description() As String
            Get
                Return ResourceManager.GetString("ReportKilo.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte de Costo por Kilo.
        '''</summary>
        Friend Shared ReadOnly Property ReportKilo_Title() As String
            Get
                Return ResourceManager.GetString("ReportKilo.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reportes.
        '''</summary>
        Friend Shared ReadOnly Property Reports_Description() As String
            Get
                Return ResourceManager.GetString("Reports.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reportes.
        '''</summary>
        Friend Shared ReadOnly Property Reports_Title() As String
            Get
                Return ResourceManager.GetString("Reports.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Centros de Costos.
        '''</summary>
        Friend Shared ReadOnly Property str124_Description() As String
            Get
                Return ResourceManager.GetString("str124.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Centros de Costos.
        '''</summary>
        Friend Shared ReadOnly Property str124_Title() As String
            Get
                Return ResourceManager.GetString("str124.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procesos.
        '''</summary>
        Friend Shared ReadOnly Property str170_Description() As String
            Get
                Return ResourceManager.GetString("str170.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procesos.
        '''</summary>
        Friend Shared ReadOnly Property str170_Title() As String
            Get
                Return ResourceManager.GetString("str170.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Obreros.
        '''</summary>
        Friend Shared ReadOnly Property str18_Description() As String
            Get
                Return ResourceManager.GetString("str18.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Obreros.
        '''</summary>
        Friend Shared ReadOnly Property str18_Title() As String
            Get
                Return ResourceManager.GetString("str18.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maquinaria.
        '''</summary>
        Friend Shared ReadOnly Property str2003_Description() As String
            Get
                Return ResourceManager.GetString("str2003.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maquinaria.
        '''</summary>
        Friend Shared ReadOnly Property str2003_Title() As String
            Get
                Return ResourceManager.GetString("str2003.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recursos.
        '''</summary>
        Friend Shared ReadOnly Property str2011_Description() As String
            Get
                Return ResourceManager.GetString("str2011.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recursos.
        '''</summary>
        Friend Shared ReadOnly Property str2011_Title() As String
            Get
                Return ResourceManager.GetString("str2011.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insumos.
        '''</summary>
        Friend Shared ReadOnly Property str2012_Description() As String
            Get
                Return ResourceManager.GetString("str2012.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insumos.
        '''</summary>
        Friend Shared ReadOnly Property str2012_Title() As String
            Get
                Return ResourceManager.GetString("str2012.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actividades.
        '''</summary>
        Friend Shared ReadOnly Property str201_Description() As String
            Get
                Return ResourceManager.GetString("str201.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actividades.
        '''</summary>
        Friend Shared ReadOnly Property str201_Title() As String
            Get
                Return ResourceManager.GetString("str201.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zonas de Trabajo.
        '''</summary>
        Friend Shared ReadOnly Property str20_Description() As String
            Get
                Return ResourceManager.GetString("str20.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zonas de Trabajo.
        '''</summary>
        Friend Shared ReadOnly Property str20_Title() As String
            Get
                Return ResourceManager.GetString("str20.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proveedores.
        '''</summary>
        Friend Shared ReadOnly Property str38_Description() As String
            Get
                Return ResourceManager.GetString("str38.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proveedores.
        '''</summary>
        Friend Shared ReadOnly Property str38_Title() As String
            Get
                Return ResourceManager.GetString("str38.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cultivos.
        '''</summary>
        Friend Shared ReadOnly Property str5001_Description() As String
            Get
                Return ResourceManager.GetString("str5001.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cultivos.
        '''</summary>
        Friend Shared ReadOnly Property str5001_Title() As String
            Get
                Return ResourceManager.GetString("str5001.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saldos de Almacen.
        '''</summary>
        Friend Shared ReadOnly Property str9205_Description() As String
            Get
                Return ResourceManager.GetString("str9205.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saldos de Almacen.
        '''</summary>
        Friend Shared ReadOnly Property str9205_Title() As String
            Get
                Return ResourceManager.GetString("str9205.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte Una Zona de Trabajo por Recursos.
        '''</summary>
        Friend Shared ReadOnly Property str9211_Description() As String
            Get
                Return ResourceManager.GetString("str9211.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte Una Zona de Trabajo por Recursos.
        '''</summary>
        Friend Shared ReadOnly Property str9211_Title() As String
            Get
                Return ResourceManager.GetString("str9211.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte Una Zona de Trabajo por Actividades.
        '''</summary>
        Friend Shared ReadOnly Property str9212_Description() As String
            Get
                Return ResourceManager.GetString("str9212.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporte Una Zona de Trabajo por Actividades.
        '''</summary>
        Friend Shared ReadOnly Property str9212_Title() As String
            Get
                Return ResourceManager.GetString("str9212.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resumen por Recursos y por Ha.
        '''</summary>
        Friend Shared ReadOnly Property str9242_Description() As String
            Get
                Return ResourceManager.GetString("str9242.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resumen por Recursos y por Ha.
        '''</summary>
        Friend Shared ReadOnly Property str9242_Title() As String
            Get
                Return ResourceManager.GetString("str9242.Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importar de Excel.
        '''</summary>
        Friend Shared ReadOnly Property str9258_Description() As String
            Get
                Return ResourceManager.GetString("str9258.Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importar de Excel.
        '''</summary>
        Friend Shared ReadOnly Property str9258_Title() As String
            Get
                Return ResourceManager.GetString("str9258.Title", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
